### ISSUE TITLE
Python 介绍以及 Python2 与 Python3 的区别 | Viki's Blog

### ISSUE THREAD

**Issue by vikiboss** [Vikiboss/vikiboss.github.io#4]
https://vikiboss.top/2020/09/05/python-introduce/ 

 Python 是一种面向对象、解释型、动态数据类型的高级程序设计脚本语言，同时也是一种功能强大而完善的通用型语言。

**Comment by Hacker-C** [comment]
浩浩大佬666，带带我

**Comment by vikiboss** [comment]
> @Hacker-C
> 浩浩大佬666，带带我

啊这  我抄来的  菜鸟教程 QAQ

**Comment by Hacker-C** [comment]
> @Vikiboss
> > @Hacker-C
> > 浩浩大佬666，带带我
> 
> 啊这  我抄来的  菜鸟教程 QAQ


> @Vikiboss
> > @Hacker-C
> > 浩浩大佬666，带带我
> 
> 啊这  我抄来的  菜鸟教程 QAQ

(。・∀・)ノ

**Comment by vikiboss** [comment]
> > @Vikiboss
> > > @Hacker-C
> > > 浩浩大佬666，带带我
> > 
> > 啊这  我抄来的  菜鸟教程 QAQ
> 
> (。・∀・)ノ

边抄边学

**Comment by Hacker-C** [comment]
> @Vikiboss
> > > @Vikiboss
> > > > @Hacker-C
> > > > 浩浩大佬666，带带我
> > > 
> > > 啊这  我抄来的  菜鸟教程 QAQ
> > 
> > (。・∀・)ノ
> 
> 边抄边学

俺也一样
